name: Generate Doxygen Documentation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate documentation
      run: |
        doxygen Doxyfile

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs-${{ github.ref_name }}
        path: doxygen/html/
        retention-days: 30

    - name: Setup Pages
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
      uses: actions/configure-pages@v4

    - name: Upload to GitHub Pages
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./doxygen/html

    - name: Deploy to GitHub Pages
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4
